# Generated by Django 3.1.2 on 2020-12-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0002_auto_20201227_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Price'),
        ),
    ]
