# Generated by Django 3.1.2 on 2020-12-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0003_auto_20201228_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
